<!DOCTYPE html>
<html>
<head>
    <style>
        .footer-container {
            padding: 10px 20px;
            border-top: 1px solid #e2e8f0;
            font-size: 10px;
            color: #64748b;
        }
        .footer-content {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .footer-left {
            flex: 1;
        }
        .footer-center {
            flex: 1;
            text-align: center;
        }
        .footer-right {
            flex: 1;
            text-align: right;
        }
        .page-number:before {
            content: "Page " counter(page) " of " counter(pages);
        }
        .confidential {
            text-transform: uppercase;
            color: #dc2626;
            font-weight: bold;
            letter-spacing: 1px;
        }
        .generated-info {
            font-style: italic;
        }
    </style>
</head>
<body>
    <div class="footer-container">
        <div class="footer-content">
            <div class="footer-left">
                <span class="confidential">Confidential</span>
            </div>
            <div class="footer-center">
                <span class="generated-info">Generated by {{ $generated_by['name'] }} on {{ $generated_by['date'] }}</span>
            </div>
            <div class="footer-right">
                <span class="page-number"></span>
            </div>
        </div>
    </div>
</body>
</html> 