version: '3.9'

services:
  app:
    image: laravelsail/php83-composer
    container_name: snd-app-app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    command: ["php", "artisan", "serve", "--host=0.0.0.0", "--port=8000"]

  node:
    image: node:22
    container_name: snd-app-node
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    command: ["npm", "run", "dev"]
    depends_on:
      - app

  postgres:
    image: postgres:16
    container_name: snd-app-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: snd-app-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
