# Nixpacks configuration for Laravel 12 + React (Vite) + Inertia.js monorepo
# Generated for production deployment

[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.curl",
  "php82Extensions.mbstring",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.pdo_sqlite",
  "php82Extensions.fileinfo",
  "php82Extensions.openssl",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.zip",
  "php82Extensions.bcmath",
  "php82Extensions.gd",
  "php82Extensions.exif",
  "composer",
  "nodejs_20",
  "yarn",
  "nginx"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache",
  "php artisan migrate --force"
]

[start]
cmd = "php-fpm -y /etc/php-fpm.conf -c /etc/php.ini && nginx -g 'daemon off;'"
