<?php

return [
    // Page titles
    'audit_logs' => 'Audit Logs',
    'gdpr_dashboard' => 'GDPR Dashboard',
    'compliance_reports' => 'Compliance Reports',
    'data_retention' => 'Data Retention',

    // Actions
    'export' => 'Export',
    'search' => 'Search',
    'searching' => 'Searching...',
    'reset' => 'Reset',
    'view' => 'View',
    'clear_filters' => 'Clear Filters',
    'generate_report' => 'Generate Report',
    'download' => 'Download',
    'approve' => 'Approve',
    'reject' => 'Reject',
    'delete' => 'Delete',
    'edit' => 'Edit',
    'save' => 'Save',
    'cancel' => 'Cancel',

    // Table headers
    'id' => 'ID',
    'date_time' => 'Date/Time',
    'user' => 'User',
    'event' => 'Event',
    'model' => 'Model',
    'model_id' => 'Model ID',
    'ip_address' => 'IP Address',
    'actions' => 'Actions',
    'status' => 'Status',
    'type' => 'Type',
    'description' => 'Description',
    'created_at' => 'Created At',
    'updated_at' => 'Updated At',

    // Filter labels
    'filter_audit_logs' => 'Filter Audit Logs',
    'search_logs' => 'Search logs...',
    'select_event' => 'Select Event',
    'select_model' => 'Select Model',
    'all_events' => 'All Events',
    'all_models' => 'All Models',
    'from_date' => 'From Date',
    'to_date' => 'To Date',
    'user_id' => 'User ID',

    // Event types
    'created' => 'Created',
    'updated' => 'Updated',
    'deleted' => 'Deleted',
    'restored' => 'Restored',
    'login' => 'Login',
    'logout' => 'Logout',
    'failed_login' => 'Failed Login',
    'password_changed' => 'Password Changed',
    'permission_granted' => 'Permission Granted',
    'permission_revoked' => 'Permission Revoked',

    // Stats
    'total_logs' => 'Total Logs',
    'active_users' => 'Active Users',
    'today_logs' => 'Today\'s Logs',
    'critical_events' => 'Critical Events',
    'total_requests' => 'Total Requests',
    'pending_requests' => 'Pending Requests',
    'completed_requests' => 'Completed Requests',
    'consent_records' => 'Consent Records',
    'compliance_score' => 'Compliance Score',
    'retention_policies' => 'Retention Policies',
    'scheduled_cleanups' => 'Scheduled Cleanups',

    // Messages
    'no_audit_logs_found' => 'No audit logs found',
    'try_adjusting_filters' => 'Try adjusting your filters to see more results',
    'system' => 'System',
    'no_data_available' => 'No data available',
    'loading' => 'Loading...',

    // GDPR specific
    'data_requests' => 'Data Requests',
    'consent_management' => 'Consent Management',
    'request_type' => 'Request Type',
    'data_export' => 'Data Export',
    'data_deletion' => 'Data Deletion',
    'data_portability' => 'Data Portability',
    'consent_given' => 'Consent Given',
    'consent_withdrawn' => 'Consent Withdrawn',
    'processing_purpose' => 'Processing Purpose',

    // Compliance Reports
    'report_name' => 'Report Name',
    'report_type' => 'Report Type',
    'generated_by' => 'Generated By',
    'file_size' => 'File Size',
    'privacy_audit' => 'Privacy Audit',
    'security_assessment' => 'Security Assessment',
    'compliance_overview' => 'Compliance Overview',
    'data_mapping' => 'Data Mapping',

    // Data Retention
    'policy_name' => 'Policy Name',
    'retention_period' => 'Retention Period',
    'last_execution' => 'Last Execution',
    'next_execution' => 'Next Execution',
    'records_affected' => 'Records Affected',
    'execution_time' => 'Execution Time',
    'execution_status' => 'Execution Status',
    'successful' => 'Successful',
    'failed' => 'Failed',
    'in_progress' => 'In Progress',

    // Time periods
    'days' => 'days',
    'months' => 'months',
    'years' => 'years',
    'never' => 'Never',

    // Validation messages
    'required_field' => 'This field is required',
    'invalid_date' => 'Invalid date format',
    'date_range_error' => 'End date must be after start date',

    // Success messages
    'export_successful' => 'Export completed successfully',
    'report_generated' => 'Report generated successfully',
    'policy_created' => 'Retention policy created successfully',
    'policy_updated' => 'Retention policy updated successfully',
    'policy_deleted' => 'Retention policy deleted successfully',

    // Error messages
    'export_failed' => 'Export failed',
    'report_generation_failed' => 'Report generation failed',
    'policy_creation_failed' => 'Failed to create retention policy',
    'policy_update_failed' => 'Failed to update retention policy',
    'policy_deletion_failed' => 'Failed to delete retention policy',
    'unauthorized_access' => 'Unauthorized access',
    'insufficient_permissions' => 'Insufficient permissions',
];
